# Sample workflow for building and deploying an Astro site to GitHub Pages
#
# To get started with Astro see: https://docs.astro.build/en/getting-started/
#
name: Deploy Astro site to VPS

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["master"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

env:
  BUILD_PATH: "." # default value when not using subfolders
  NODE_ENV: "production"

jobs:
  deploy:
    name: Deploy to VPS
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Deploy to VPS
        uses: appleboy/scp-action@v0.1.7
        with:
          host: "43.134.87.90"
          username: "root"
          password: ${{ secrets.VPS_PASSWORD }}
          source: "./*"
          target: "/root/porto-radit"
          
      - name: Build and Start on VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: "43.134.87.90"
          username: "root"
          password: ${{ secrets.VPS_PASSWORD }}
          script: |
            cd /root/porto-radit
            npm install
            npm run build
            npm install pm2 -g
            pm2 delete "landing-page:demo" || true
            pm2 start ecosystem.config.json --env production
            pm2 save
            pm2 startup
